import React from 'react';

  export  const categories = [
        {
          name: "Automotive",
          children: [
            {
              name: "Automobile Related",
              children: [
                "Automobile Accessories",
                "Automobile Garage Related",
                "Automobile Maintanance Related",
                "Automobile Spares / Tyre",
                "Road Safety Equipments",
                "Security & Helpline Services",
                "Web Based/Online Platform",
              ],
            },
            {
              name: "Commercial Vehicles",
              children: [
                "Commercial Vehicles Bus/Trucks",
                "Commercial Electric Vehicles (EV)",
                "Off Road / All Terrain Vehicles",
                "Three Wheeler (Auto) Showroom",
                "Tractors",
              ],
            },
            {
              name: "Four Wheeler",
              children: [
                "Car Exterior Parts",
                "Car Interior Accessories",
                "Car Interior Spare Parts",
                "Car Maintanance & Repair Services",
                "Car Rental",
                "Car Reselling",
                "Car Showroom",
                "Car Wash / Ceramic Coating / Detailing",
                "Electric Vehicles Four Wheelers (EV)",
              ],
            },
            {
              name: "Two Wheeler",
              children: [
                "Bicycle",
                "Bike Maintanance & Repair Services",
                "Bike Rental",
                "Bike Showroom",
                "Bike Wash",
                "Biker's Accessories",
                "Electric Vehicles Two Wheelers (EV)",
              ],
            },
          ],
        },
        {
          name: "Beauty & Health",
          children: [
            {
              name: "Beauty Aesthetics & Supplies",
              children: [
                "Bath Products",
                "Beauty Equipments",
                "Beauty Salons/ Unisex Salons/ Spa",
                "Cosmetic Accessories",
                "Cosmetics & Beauty Product Stores",
                "Pet Grooming",
                "Tattoo, Piercing & Nail Art",
              ],
            },
            {
              name: "Health Care",
              children: [
                "Ayurvedic & Herbal Products",
                "Fitness & Gym Equipments",
                "Fitness Centres",
                "Health & Wellness Centres",
                "Health Care Services",
                "Medical Equipment & Supplies",
                "Nutrition & Supplements",
                "Pharmacy",
              ],
            },
            {
              name: "Wellness",
              children: [
                "Fitness & Gym Equipments",
                "Health & Wellness Centres",
                "Health Care Services",
                "Medical Equipment & Supplies",
                "Nutrition & Supplements",
                "Pharmacy",
              ],
            },
          ],
        },
        {
          name: "Business Services",
          children: [
            {
              name: "Advertising & Marketing",
              children: [
                "Advertising & Marketing Agencies",
                "Digital Marketing",
                "Event Management",
                "Public Relations",
                "Social Media Marketing",
              ],
            },
            {
              name: "Business Consulting",
              children: [
                "BPO",
                "Business",
                "Career Counseling",
                "Financial",
                "HR & Recruitment",
                "Immigration",
                "Legal",
                "Matrimonial",
                "Others Consultancy",
                "Real Estate",
                "Service For SMEs",
                "Technology",
              ],
            },
            {
              name: "Financial Services",
              children: [
                "Accounting & Auditing Services",
                "Equity & Debt Providers",
                "Finance Advisors & Brokers",
                "Financial Investment & Trading",
                "Foreign Exchange (FOREX)",
                "Insurance",
                "Microfinance",
                "Non Banking Financial Company (NBFC)",
                "Others Financial",
                "Payment Solution Services",
                "Post Office Services",
                "Tax Consulting Services",
                "Wealth Management",
              ],
            },
            {
              name: "Household Services",
              children: [
                "Electrical & Plumbing Services",
                "Facility Management",
                "Gardening Services",
                "Home Appliances Repair Services",
                "Home Renovation Services",
                "Home Safety & Security",
                "Housekeeping",
                "Institutional/Facility Cleaning",
                "Laundry & Dry Cleaning",
                "Pest Control",
                "Repair Services",
              ],
            },
            {
              name: "IT Services",
              children: [
                "Application Development",
                "Cloud Services",
                "Computer Hardware & Software",
                "Data Science & Analytics",
                "Domain & Hosting Services",
                "ERP Solutions",
                "IT Consulting",
                "IT Infrastructure Management",
                "Mobile App Development",
                "Networking & Security Services",
                "Software Development",
                "Web Development",
              ],
            },
            {
              name: "Logistics & Transportation",
              children: [
                "Cargo & Freight Services",
                "Courier Services",
                "Freight Forwarding",
                "International Logistics",
                "Logistics Aggregators",
                "Packers & Movers",
                "Transportation",
              ],
            },
            {
              name: "Real Estate",
              children: ["Commercial Real Estate", "Residential Real Estate"],
            },
            {
              name: "Travel & Tourism",
              children: [
                "Adventure Tourism",
                "Air Ticketing Services",
                "Car Rentals",
                "Cruise Services",
                "Domestic Tour Operators",
                "Foreign Tour Operators",
                "Hotel & Resort Booking Services",
                "Railway Ticketing Services",
                "Travel Insurance",
              ],
            },
            {
              name: "waste Management & Recycling",
              children: [
                "E-Waste Recycling",
                "Hazardous Waste Management",
                "Plastic Waste Management",
                "Waste Collection & Disposal",
                "Waste Recycling",
              ],
            },
          ],
        },
        {
          name: "Education & Training",
          children: [
            {
              name: "Coaching & Tutoring",
              children: [
                "CAD/CAM/CAE & Multimedia",
                "Competitive Exam Coaching Institute",
                "Online Coaching",
                "Robotics & Technical Training/ AI",
                "School Tutoring",
              ],
            },
            {
              name: "Early Education",
              children: ["Day Care", "Montessori Schools", "Preschools/Play Schools"],
            },
            {
              name: "Education Consultants",
              children: ["Education Consultants", "Overseas Education Consultants"],
            },
            {
              name: "Education Services",
              children: [
                "Education Services",
                "Educational Institutions",
                "Educational Software & Apps",
                "Online Learning Platforms",
              ],
            },
            {
              name: "Higher Education",
              children: [
                "Degree/Diploma Colleges",
                "Distance Learning Centres",
                "Professional Education Colleges",
                "Universities (including Overseas Franchises)",
              ],
            },
            {
              name: "online Learning",
              children: [
                "Certification Course Coaching",
                "Corporate Training",
                "Entrance Examination Coaching",
                "Foreign Language Coaching",
                "Online Learning/E-learning",
                "Other Online Education",
                "Professional Education Coaching",
              ],
            },
            {
              name: "Vocational Training",
              children: [
                "Aviation & Hospitality Training Institute",
                "BPO/KPO Training Institutes",
                "Banking & Insurance Training Institute",
                "Beauty & Wellness Training Institute",
                "Financial Advisory",
                "HR Certification Institute",
                "IT Education",
                "Language Schools",
                "Other Vocational Training",
                "Paramedical/Medical Training",
                "Retail Training Institutes",
                "Skills / Personality Development",
              ],
            },
          ],
        },
        {
          name: "Fashion & Lifestyle",
          children: [
            {
              name: "Accessories",
              children: [
                "Bags & Luggage",
                "Belt & Wallets",
                "Eyewear",
                "Fashion Accessories",
                "Footwear",
                "Jewellery",
                "Watches",
              ],
            },
            {
              name: "Clothing",
              children: [
                "Apparel & Garments",
                "Clothing Accessories",
                "Fabric & Textile",
                "Footwear",
                "Garment Manufacturing",
                "Jewellery",
                "Leather Garments",
                "Textile Machinery & Equipment",
              ],
            },
            {
              name: "Cosmetics & Beauty Products",
              children: [
                "Beauty & Personal Care",
                "Cosmetics & Beauty Products",
                "Cosmetics & Beauty Product Stores",
                "Health & Wellness Centres",
                "Medical Equipment & Supplies",
              ],
            },
          ],
        },
        {
          name: "Food & Beverages",
          children: [
            {
              name: "Bakery, Sweets & Ice Cream",
              children: [
                "Bakery",
                "Bakery Equipment & Supplies",
                "Bakery Ingredients",
                "Bakery Shops",
                "Bakery Stores",
                "Ice Cream",
                "Ice Cream Equipment & Supplies",
                "Ice Cream Shops",
                "Ice Cream Stores",
              ],
            },
            {
              name: "Catering & Food Services",
              children: [
                "Catering Services",
                "Catering Equipment & Supplies",
                "Catering Ingredients",
                "Catering Shops",
                "Catering Stores",
              ],
            },
            {
              name: "Cafe & Parlors",
              children: [
                "Cafe",
                "Cafe Equipment & Supplies",
                "Cafe Ingredients",
                "Cafe Shops",
                "Cafe Stores",
              ],
            },
            {
              name: "Food & Beverage",
              children: [
                "Beverages",
                "Beverages Equipment & Supplies",
                "Beverages Ingredients",
                "Beverages Shops",
                "Beverages Stores",
              ],
            },
            {
              name: "Restaurant & Night Clubs",
              children: [
                "Restaurant",
                "Restaurant Equipment & Supplies",
                "Restaurant Ingredients",
                "Restaurant Shops",
                "Restaurant Stores",
              ],
            },
          ],
        },
        {
          name: "HomeBased Business Services",
          children: [
            {
              name: "Beauty & Personal Care",
              children: [
                "Beauty & Personal Care",
                "Cosmetics & Beauty Products",
                "Cosmetics & Beauty Product Stores",
                "Health & Wellness Centres",
                "Medical Equipment & Supplies",
              ],
            },
            {
              name: "Business Services",
              children: [
                "Accounting & Auditing Services",
                "Equity & Debt Providers",
                "Finance Advisors & Brokers",
                "Financial Investment & Trading",
                "Foreign Exchange (FOREX)",
                "Insurance",
                "Microfinance",
                "Non Banking Financial Company (NBFC)",
                "Others Financial",
                "Payment Solution Services",
                "Post Office Services",
                "Tax Consulting Services",
                "Wealth Management",
              ],
            },
            {
              name: "repair & Maintenance",
              children: [
                "Electrical & Plumbing Services",
                "Facility Management",
                "Gardening Services",
                "Home Appliances Repair Services",
                "Home Renovation Services",
                "Home Safety & Security",
                "Housekeeping",
                "Institutional/Facility Cleaning",
                "Laundry & Dry Cleaning",
                "Pest Control",
                "Repair Services",
              ],
            },
            {
              name: "technology & Releated",
              children: [
                "Application Development",
                "Cloud Services",
                "Computer Hardware & Software",
                "Data Science & Analytics",
                "Domain & Hosting Services",
                "ERP Solutions",
                "IT Consulting",
                "IT Infrastructure Management",
                "Mobile App Development",
                "Networking & Security Services",
                "Software Development",
                "Web Development",
              ],
            },
          ],
        },
        {
          name: "Hotels & Resorts",
          children: [
            {
              name: "Hotels",
              children: ["Hotel Booking Services", "Hotels & Resorts"],
            },
            {
              name: "Resorts",
              children: ["Hotel Booking Services", "Hotels & Resorts"],
            },
            {
              name: "Travel & Tourism",
              children: [
                "Adventure Tourism",
                "Air Ticketing Services",
                "Car Rentals",
                "Cruise Services",
                "Domestic Tour Operators",
                "Foreign Tour Operators",
                "Hotel & Resort Booking Services",
                "Railway Ticketing Services",
                "Travel Insurance",
              ],
            },
            {
              name: "Travel Agents",
              children: ["Travel Agents", "Travel Booking Services"],
            },
          ],
        },
        {
          name: "Reatils",
          children: [
            {
              name: "Books & Stationery",
              children: ["Books & Stationery", "Books & Stationery Stores"],
            },
            {
              name: "consumer Durables",
              children: [
                "Consumer Electronics",
                "Consumer Electronics Stores",
                "Consumer Goods",
                "Consumer Goods Stores",
              ],
            },
            {
              name: "E-Reatail",
              children: ["E-Commerce", "E-Commerce Stores"],
            },
            {
              name: "Fashion",
              children: [
                "Apparel & Garments",
                "Clothing Accessories",
                "Fabric & Textile",
                "Footwear",
                "Garment Manufacturing",
                "Jewellery",
                "Leather Garments",
                "Textile Machinery & Equipment",
              ],
            },
            {
              name: "Home & Office",
              children: [
                "Home & Office Appliances",
                "Home & Office Appliances Stores",
              ],
            },
            {
              name: "supermarket & Grocery",
              children: [
                "Dairy/F&V Stores",
                "Department & Convenience Stores",
                "Food Marts",
                "Gourmet Stores",
                "Grocery Stores",
                "Kiosks",
                "Meat & Chicken Shops",
                "Organic Products",
                "Pet Stores",
                "Superstores",
                "Wine Shops",
              ],
            },
          ],
        },
        {
          name: "Sports & Fitness & entertainment",
          children: [
            {
              name: "Fitness & Gym",
              children: [
                "Fitness & Gym Equipments",
                "Fitness Centres",
                "Health & Wellness Centres",
                "Health Care Services",
                "Medical Equipment & Supplies",
                "Nutrition & Supplements",
                "Pharmacy",
              ],
            },
            {
              name: "Sports & Games",
              children: [
                "Sports & Games Accessories",
                "Sports & Games Equipments",
                "Sports & Games Stores",
              ],
            },
            {
              name: "entertainment",
              children: [
                "Event Management",
                "Event Organizers",
                "Event Planning",
                "Event Production",
                "Event Rentals",
              ],
            },
          ],
        },
      ];

export default categories;