name: Deploy to Hostinger VPS

on:
  push:
    branches: [ "rajan" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $VPS_HOST >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_HOST: ${{ secrets.VPS_HOST }}

      - name: Deploy on VPS
        run: |
          ssh $VPS_USER@$VPS_HOST "
            cd /root/franchise_Backend &&
            git pull &&
            npm install &&
            pm2 restart franchise_backend || pm2 start index.js --name franchise_backend 
          "
        env:
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
